version: '3.7'

services:
  postgres:
      image: postgres
      container_name: postgres-outbox
      environment:
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_USER: "postgres"
      ports:
        - "5432:5432"
      volumes:
        - ./postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    restart: always

volumes:
  rabbitmq_data: